### ISSUE TITLE
Server tests for 'basic' requests

### ISSUE THREAD

**Issue by willsimmons** [newtonian-platypus/greenCast#12]
get user aka login - should send user
get podcasts  or / - should send top episodes
get channel - should send a single channel's episodes
get podcast - should send a single podcast

**Comment by chasestarr** [comment]
Created PR: https://github.com/newtonian-platypus/greenCast/pull/32

Wrote tests for most that I thought of. I like the idea of top podcasts as well as login/logout routes. Those will need to be added
